repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
      - id: check-symlinks
  - repo: https://github.com/google/yamlfmt
    rev: v0.21.0
    hooks:
      - id: yamlfmt
        types: [yaml]
  - repo: local
    hooks:
      - id: golangci-lint
        name: golangci-lint
        entry: go tool -modfile=tools.mod golangci-lint run
        language: system
        types: [go]
        pass_filenames: false
      - id: govulncheck
        name: govulncheck
        entry: go tool -modfile=tools.mod govulncheck ./...
        language: system
        types: [go]
        pass_filenames: false
